version: "3.8"

networks:
  webui_net:
    name: webui_net
    driver: bridge

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - webui_net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - webui_net

  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.22   # pin a version (recommended)
    container_name: openwebui
    restart: unless-stopped
    environment:
      # --- Providers (UI-only) ---
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      PERPLEXITY_API_KEY: "${PERPLEXITY_API_KEY}"

      # --- Signups & user defaults ---
      # First run: leave ENABLE_SIGNUP unset (defaults to true) or set to "true" in .env
      ENABLE_SIGNUP: "${ENABLE_SIGNUP}"
      DEFAULT_USER_ROLE: "${DEFAULT_USER_ROLE}"   # e.g., "pending" (recommended), "user"

      # Helps WebUI generate correct links (optional but nice)
      WEBUI_URL: "https://${CHAT_DOMAIN}"

      # --- Proxy routing + TLS ---
      VIRTUAL_HOST: "${CHAT_DOMAIN}"
      LETSENCRYPT_HOST: "${CHAT_DOMAIN}"
      LETSENCRYPT_EMAIL: "${LE_EMAIL}"
      VIRTUAL_PORT: "8080"
    volumes:
      - ./openwebui-data:/app/backend/data
    expose:
      - "8080"
    networks:
      - webui_net

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:

