version: "3.9"

networks:
  proxy:
    name: proxy
    driver: bridge

services:
  # Reverse proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - proxy

  # Let's Encrypt companion for auto TLS
  nginx-proxy-acme:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: "${LE_EMAIL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - proxy

  # OpenWebUI (UI only, uses API keys)
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      # OPENAI_API_BASE_URL: "${OPENAI_API_BASE_URL}"
      # ANTHROPIC_API_BASE_URL: "${ANTHROPIC_API_BASE_URL}"

      # nginx-proxy routing + TLS
      VIRTUAL_HOST: "${CHAT_DOMAIN}"
      LETSENCRYPT_HOST: "${CHAT_DOMAIN}"
      LETSENCRYPT_EMAIL: "${LE_EMAIL}"
      VIRTUAL_PORT: "8080"
    volumes:
      - ./openwebui-data:/app/backend/data
    expose:
      - "8080"
    networks:
      - proxy

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
